# Configuration for the roar CLI
# https://github.com/JanMalch/roar

branch = "main"

[[update]]
file = "app/build.gradle.kts"
find = "val vName = "
replace = "val vName = \"{{version}}\""

[changelog]
include = ["feat", "fix", "perf"]
url_commit = "https://github.com/JanMalch/pocpic/commit/{{hash}}"
url_browse_at_tag = "https://github.com/JanMalch/pocpic/tree/v{{version}}"
url_compare_tags = "https://github.com/JanMalch/pocpic/compare/v{{previous}}...v{{version}}"
url_commits_for_tag = "https://github.com/JanMalch/pocpic/commits/v{{version}}"
url_upcoming = "https://github.com/JanMalch/pocpic/compare/v{{version}}...main"