[versions]
agp = "8.7.0"
appcompat = "1.7.0"
coil = "3.0.0-rc01"
datastore = "1.1.1"
glance-appwidget = "1.1.0"
kotlinx-datetime = "0.6.1"
material = "1.12.0"
kotlin = "2.0.21"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
lifecycle-runtime-ktx = "2.8.6"
activity-compose = "1.9.2"
compose-bom = "2024.09.03"
hilt = "2.52"
android-hilt = "1.2.0"
ksp = "2.0.21-1.0.25"
coroutines = "1.9.0"
icons = "1.7.3" # FIXME: needed?!
landscapist = "2.3.2"
documentfile = "1.0.1"
hilt-navigation-compose = "1.2.0"
work-runtime-ktx = "2.9.1"
google-oss = "17.1.0"
google-oss-plugin = "0.10.6"
protobuf = "3.23.2" # "3.23.3" is broken
protobuf-plugin = "0.9.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance-appwidget" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance-appwidget" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "icons" }
ui-images = { group = "com.github.skydoves", name = "landscapist-glide", version.ref = "landscapist" }
material3 = { group = "androidx.compose.material3", name = "material3" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "android-hilt" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "android-hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "android-hilt" }
google-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "google-oss" }
google-oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "google-oss-plugin" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }

[bundles]
ui = ["activity-compose", "ui", "ui-graphics", "ui-tooling-preview", "material3", "ui-icons-extended", "ui-images"]
hilt = ["hilt", "hilt-common", "hilt-work"]
ui-debug = ["ui-tooling", "ui-test-manifest"]
ui-widget = ["androidx-glance-appwidget", "androidx-glance-material3"]
coroutines = ["coroutines-core", "coroutines-android"]
datastore = ["androidx-datastore", "protobuf-java", "protobuf-kotlin"]